run-dist:
	./build/install/app/bin/app

start:
	./gradlew run

help:
	./build/install/app/bin/app -h

build:
	./gradlew build

clean:
	./gradlew clean

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain checkstyleTest

build-run: build run

.PHONY: build